# Generated by Django 2.0.1 on 2018-01-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=500, verbose_name='Должность')),
                ('post_genitive', models.CharField(max_length=500, verbose_name='Должность в родительном падеже')),
                ('post_dative', models.CharField(max_length=500, verbose_name='Должность в дательном падеже')),
                ('full_name', models.CharField(max_length=1000, verbose_name='ФИО')),
                ('full_name_genitive', models.CharField(max_length=1000, verbose_name='ФИО в родительном падеже')),
                ('full_name_dative', models.CharField(max_length=1000, verbose_name='ФИО в дательном падеже')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
