# Generated by Django 2.0.1 on 2018-01-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_program', '0002_auto_20180107_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='order_to_open',
            field=models.FilePathField(blank=True, null=True, path='E:\\python\\PyCharm Projects\\accounting-educational-programs\\src\\media', verbose_name='Приказ об открытии'),
        ),
    ]
