# Generated by Django 2.0.1 on 2018-01-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational_program', '0003_auto_20180107_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='order_to_open',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Приказ об открытии'),
        ),
    ]
